# Generated by Django 4.0.3 on 2022-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0002_category_newstimeseries_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
