# Generated by Django 4.0.3 on 2022-04-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0003_alter_category_options_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
