# Generated by Django 4.0.3 on 2022-04-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0005_remove_newstimeseries_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstimeseries',
            name='city',
            field=models.ManyToManyField(to='newsapi.city'),
        ),
        migrations.AddField(
            model_name='newstimeseries',
            name='country',
            field=models.ManyToManyField(to='newsapi.country'),
        ),
        migrations.AddField(
            model_name='newstimeseries',
            name='mentioned',
            field=models.ManyToManyField(to='newsapi.mentioned'),
        ),
        migrations.AddField(
            model_name='newstimeseries',
            name='state',
            field=models.ManyToManyField(to='newsapi.state'),
        ),
    ]
