# Generated by Django 4.0.3 on 2022-04-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0006_newstimeseries_city_newstimeseries_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstimeseries',
            name='city',
        ),
        migrations.AddField(
            model_name='newstimeseries',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsapi.city'),
        ),
        migrations.RemoveField(
            model_name='newstimeseries',
            name='country',
        ),
        migrations.AddField(
            model_name='newstimeseries',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsapi.country'),
        ),
        migrations.RemoveField(
            model_name='newstimeseries',
            name='mentioned',
        ),
        migrations.AddField(
            model_name='newstimeseries',
            name='mentioned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsapi.mentioned'),
        ),
        migrations.RemoveField(
            model_name='newstimeseries',
            name='state',
        ),
        migrations.AddField(
            model_name='newstimeseries',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsapi.state'),
        ),
    ]
