# Generated by Django 4.0.3 on 2022-04-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0007_remove_newstimeseries_city_newstimeseries_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstimeseries',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
