# Generated by Django 4.0.3 on 2022-04-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0008_alter_newstimeseries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstimeseries',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newstimeseries',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newstimeseries',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newstimeseries',
            name='source_url',
            field=models.TextField(null=True),
        ),
    ]
