# Generated by Django 4.0.3 on 2022-04-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0009_alter_newstimeseries_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstimeseries',
            name='sentiment_compound',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='newstimeseries',
            name='sentiment_neg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='newstimeseries',
            name='sentiment_neu',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='newstimeseries',
            name='sentiment_pos',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='newstimeseries',
            unique_together={('author', 'publication', 'title')},
        ),
    ]
